### ISSUE TITLE
Current version of Guzzle library do not work with PHP 7

### ISSUE THREAD

**Issue by steinmb** [smbjorklund/cellproject#13]
The composer file currently used define a too old version. Running it in test and 7.x. give. Related to issue #12 

```
drush -l cellproject.local ms
PHP Fatal error:  Redefinition of parameter $_ in /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/libraries/composer/guzzlehttp/ringphp/src/Client/StreamHandler.php on line 313

Fatal error: Redefinition of parameter $_ in /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/libraries/composer/guzzlehttp/ringphp/src/Client/StreamHandler.php on line 313
```

## Suggested fix

Upgrade to newer version, it was fixed [back in 2015](https://github.com/guzzle/guzzle/issues/1015)
By updating `migrate_oaipmh` it also push libraries to the newer versions that work with a modern PHP 7.0 and newer versions.

## Adding adding a full stack trace

```
HP Stack trace:
PHP   1. {main}() /Users/steinmb/.composer/vendor/drush/drush/drush.php:0
PHP   2. drush_main() /Users/steinmb/.composer/vendor/drush/drush/drush.php:12
PHP   3. Drush\Boot\DrupalBoot7->bootstrap_and_dispatch() /Users/steinmb/.composer/vendor/drush/drush/includes/preflight.inc:66
PHP   4. drush_dispatch() /Users/steinmb/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php:67
PHP   5. drush_command() /Users/steinmb/.composer/vendor/drush/drush/includes/command.inc:199
PHP   6. _drush_invoke_hooks() /Users/steinmb/.composer/vendor/drush/drush/includes/command.inc:231
PHP   7. drush_migrate_status() /Users/steinmb/.composer/vendor/drush/drush/includes/command.inc:422
PHP   8. migrate_migrations() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/modules/ajout-nt2/migrate/migrate.drush.inc:314
PHP   9. MigrationBase::getInstance() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/modules/ajout-nt2/migrate/migrate.module:76
PHP  10. CellNodeMigration->__construct() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/modules/ajout-nt2/migrate/includes/base.inc:647
PHP  11. CellMigrateSourceOaiPmh->__construct() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/modules/custom/cell_migrate_oaipmh/includes/migration.inc:148
PHP  12. Phpoaipmh\Client->__construct() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/modules/ajout-nt2/migrate_oaipmh/includes/oaipmh.inc:65
PHP  13. Phpoaipmh\HttpAdapter\GuzzleAdapter->__construct() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/libraries/composer/caseyamcl/phpoaipmh/src/Phpoaipmh/Client.php:62
PHP  14. GuzzleHttp\Client->__construct() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/libraries/composer/caseyamcl/phpoaipmh/src/Phpoaipmh/HttpAdapter/GuzzleAdapter.php:31
PHP  15. GuzzleHttp\Client::getDefaultHandler() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/libraries/composer/guzzlehttp/guzzle/src/Client.php:92
PHP  16. spl_autoload_call() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/libraries/composer/guzzlehttp/guzzle/src/Client.php:121
PHP  17. Composer\Autoload\ClassLoader->loadClass() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/libraries/composer/guzzlehttp/guzzle/src/Client.php:121
PHP  18. Composer\Autoload\includeFile() /Users/steinmb/.composer/vendor/composer/ClassLoader.php:322

Fatal error: Redefinition of parameter $_ in /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/libraries/composer/guzzlehttp/ringphp/src/Client/StreamHandler.php on line 313

Call Stack:
    0.0019     354272   1. {main}() /Users/steinmb/.composer/vendor/drush/drush/drush.php:0
    0.0034     500424   2. drush_main() /Users/steinmb/.composer/vendor/drush/drush/drush.php:12
    0.2583    8876272   3. Drush\Boot\DrupalBoot7->bootstrap_and_dispatch() /Users/steinmb/.composer/vendor/drush/drush/includes/preflight.inc:66
    0.9718   35805504   4. drush_dispatch() /Users/steinmb/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php:67
    1.0953   37536840   5. drush_command() /Users/steinmb/.composer/vendor/drush/drush/includes/command.inc:199
    1.0955   37536936   6. _drush_invoke_hooks() /Users/steinmb/.composer/vendor/drush/drush/includes/command.inc:231
    1.1041   37782704   7. drush_migrate_status() /Users/steinmb/.composer/vendor/drush/drush/includes/command.inc:422
    1.1043   37783048   8. migrate_migrations() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/modules/ajout-nt2/migrate/migrate.drush.inc:314
    1.1376   38462024   9. MigrationBase::getInstance() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/modules/ajout-nt2/migrate/migrate.module:76
    1.1442   38477064  10. CellNodeMigration->__construct() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/modules/ajout-nt2/migrate/includes/base.inc:647
    1.1469   38502344  11. CellMigrateSourceOaiPmh->__construct() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/modules/custom/cell_migrate_oaipmh/includes/migration.inc:148
    1.1480   38516248  12. Phpoaipmh\Client->__construct() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/modules/ajout-nt2/migrate_oaipmh/includes/oaipmh.inc:65
    1.1531   38656704  13. Phpoaipmh\HttpAdapter\GuzzleAdapter->__construct() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/libraries/composer/caseyamcl/phpoaipmh/src/Phpoaipmh/Client.php:62
    1.1531   38656832  14. GuzzleHttp\Client->__construct() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/libraries/composer/caseyamcl/phpoaipmh/src/Phpoaipmh/HttpAdapter/GuzzleAdapter.php:31
    1.1600   38813768  15. GuzzleHttp\Client::getDefaultHandler() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/libraries/composer/guzzlehttp/guzzle/src/Client.php:92
    1.1645   38948968  16. spl_autoload_call() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/libraries/composer/guzzlehttp/guzzle/src/Client.php:121
    1.1645   38949032  17. Composer\Autoload\ClassLoader->loadClass() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/libraries/composer/guzzlehttp/guzzle/src/Client.php:121
    1.1646   38949224  18. Composer\Autoload\includeFile() /Users/steinmb/.composer/vendor/composer/ClassLoader.php:322

Drush command terminated abnormally due to an unrecoverable error.                                                                                                        [error]
Error: Redefinition of parameter $_ in
/Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/libraries/composer/guzzlehttp/ringphp/src/Client/StreamHandler.php, line 313
```

**Comment by steinmb** [comment]
Addressed this while working on issue #16 - Nothing left in here I think.
